### ISSUE TITLE
Different definition for guidelines in fontinfo.plist and .glif files. 

### ISSUE THREAD

**Issue by schriftgestalt** [unified-font-object/ufo-spec#225]
In .glif files there are default values for x, y, and angles. So if you can omit values that are zero. So this:
```
<guideline x="362.67" y="388.21"/>
```
means that the angle is zero (horizontal).

But in fontinfo.plist, there are no default values and that means that you always have to specify all attributes, even if they are zero. So this: 
```
    <key>guidelines</key>
    <array>
      <dict>
        <key>x</key>
        <real>-2.875</real>
        <key>y</key>
        <integer>330</integer>
      </dict>
    </array>
```
will throw an error.

I’m very much in favor of omitting default data to save file size and parsing/writing time. 
But at least, the requirements should be consistent.

**Comment by justvanrossum** [comment]
I agree that it would be better if the global and local guideline definitions would be the same with respect to default values.

**Comment by schriftgestalt** [comment]
see also: https://github.com/fonttools/fonttools/issues/3537

**Comment by benkiel** [comment]
Welp. We clarified the guideline definition in #134, but clearly didn't update it in font info. This is on me. Are we ok with updating the definition there to match, @typesupply @anthrotype ?

**Comment by anthrotype** [comment]
Sounds good to me, thanks for catching this

**Comment by anthrotype** [comment]
no wait! now I remember.. The change in https://github.com/unified-font-object/ufo-spec/pull/134 was let's say a bit controversial which is why ufoLib was not updated to match that immediately, but then somehow I dropped the ball and didn't follow up on this.

see my comment at https://github.com/unified-font-object/ufo-spec/pull/134#issuecomment-1568785485

the problem is defaulting the omitted values to 0 will lead to situations whereby old, valid files could be interpreted differently by a new guideline parser 

> a guide that was encoded as <guideline x=10> before would be interpreted as a vertical line passing through x=10; whereas now, since angle defaults to 0, it would be interpreted as an horizontal line

what do we do now?...

**Comment by schriftgestalt** [comment]
Maybe we can special case the "x" only guides for now? All other cases are should be handled properly.

**Comment by anthrotype** [comment]
"special case" how exactly?
if you start adding complicated exceptions, you may well revert to the old guidelines which at least were explicit and non-ambiguous.
Making the spec change #134 without bumping the minor version was a mistake.

**Comment by schriftgestalt** [comment]
Right now, we have several special cases (only "x", only "y" …). That change will reduce that to 1: if only "x" is set, set angle to 90. That should be mentioned in the spec with a big warning. 

A new version number would have need better, I agree.

**Comment by anthrotype** [comment]
> if only "x" is set, set angle to 90.

a guideline like `{"x": 10, "angle": 90}` (i.e. x is set, y is not set, angle is set) would not be valid when parsed using the old strict logic (when angle is set, both x and y must be set).
To make it work with both the old and new guideline logic, you'd have to explicitly set y=0 as well, making the exception even more exceptional.
It's not only a problem of ensuring new files can be parsed by old parsers (which can be upgraded), but also perhaps more importantly that old files (e.g. those where `{"x": 10}` meant a 90-degree vertical guideline at x=10, y=0, not an horizontal guideline passing through (10, 0)) continue to be interpreted the same way by the new parsers.
Are you suggesting that, when parsing a guideline, if only x is set (neither y nor angle are set), then angle should default to 90, otherwise defaults to 0?

The status quo is not good either. Maybe we do need to belatedly bump the (minor?) version after all, and tie the new guideline defaults explicitly to the new UFO version.

**Comment by schriftgestalt** [comment]
> To make it work with both the old and new guideline logic, you'd have to explicitly set y=0 as well, making the exception even more exceptional.

Not an exception. That's what the default values ​​are for. 

> Are you suggesting that, when parsing a guideline, if only x is set (neither y nor angle are set), then angle should default to 90, otherwise defaults to 0?

Yes.

**Comment by anthrotype** [comment]
@benkiel @typesupply @typemytype @justvanrossum @belluzj 

what do you guys think if we reverted #134? Not only the changes were inconsistently made only for the GLIF guidelines and not for the global fontinfo.plist ones, but the 'reference' implementation in fontTools.ufoLib has never been updated to match that. Also norad I see it's still using the old defaults. It's basically only Glyphs.app built-in UFO export that started emitting such backward incompatible guidelines.
I don't see a way to reconcile the proposed default-to-0 changes in a backward compatible way, i.e. one whereby old parsers continue to parse newly written files, or new parsers can parse old files.
Note that I'm not opposed to reintroduce a similar change in a new UFO minor version.
IIRC the UFO spec change was prompted by some fontParts issue, https://github.com/robotools/fontParts/issues/67
What's the status of that, and what the implications of reverting the spec change?

**Comment by typesupply** [comment]
> what do you guys think if we reverted https://github.com/unified-font-object/ufo-spec/pull/134?

I'm fine with that. I favor explicit over conditional interpretation in the spec these days, but there's a lot of other stuff I would change if there were no repercussions. 😆 So, if going back to less explicit is the smoothest solution, go for it.

> IIRC the UFO spec change was prompted by some fontParts issue, https://github.com/robotools/fontParts/issues/67
> What's the status of that, and what the implications of reverting the spec change?

fontParts can be changed quickly so it's not a big deal.

**Comment by benkiel** [comment]
Am also ok reverting. This was t as well thought through as it should have been, will take ownership of that.

fontParts thing can change easily

**Comment by benkiel** [comment]
@anthrotype do you have time to PR that revert?

**Comment by anthrotype** [comment]
I'm busy with some internal training this week, and then on holidays. Do you mind doing that?

**Comment by benkiel** [comment]
@anthrotype sure, done: hope you have a good holiday!
