### ISSUE TITLE
Allow background image to be JPEG?

### ISSUE THREAD

**Issue by justvanrossum** [unified-font-object/ufo-spec#234]
This makes so much more sense for scans than PNG.

**Comment by benkiel** [comment]
I am ok with that, not sure the reason why not, but maybe @typesupply remembers.

**Comment by typesupply** [comment]
This decision was publicly made over 12 years ago, but I _absolutely_ remember some of the nightmare making it.

- I wanted to allow a variety of image types but actually specifying JPEG or TIFF in an unambiguous way was extremely hard because there are so many variations. We could say "JPEG" in abstract, but which version(s) and how do we tell tools to enforce it? That was far out of the scope of the UFO spec.
- There had been a lot of patent concerns raised by members of the Free Software Community about various parts of UFO and I didn't want to repeat that trouble. So, I did a lot of research on potential issues that could be raised. I remember one in particular. The UFO 3 spec was written in 2011-12 and a company was going around and suing organizations for patent infringement involving JPEG. [Note the first sentence in the last paragraph here.](https://en.wikipedia.org/wiki/JPEG#Patent_controversy)
- JPEG is lossy. If a tool uses the import/export model, there could be degradation with repeated read/writes if the write happens to a new file.

PNG was, at least at the time, clean, clear, compressed, lossless and unencumbered. It wasn't ideal, but it was the only option.

**Comment by justvanrossum** [comment]
I was afraid it was something like that :-( I forgot, but now vague memories of this discussion reappear.

While not being a lawyer, I can't imagine a specification that merely *mentions* the JPEG standard would be in more trouble than a library like PIL/Pillow that ships under an MIT license, and contains a fairly complete JPEG *implementation*.

**Comment by typesupply** [comment]
Yeah, I'm guessing we would have been okay legally but this was in the days of lawsuits being thrown around just to see what would stick.

**Comment by justvanrossum** [comment]
I'd suggest to update the spec to include the abstract "JPEG", and saying the level of support is implementation-dependent. Or is that too low effort?

**Comment by typesupply** [comment]
If we make the change:

- There would need to be code changes to ufoLib, validators and normalizers. Here are two places off the top of my head: [ufoLib](https://github.com/fonttools/fonttools/blob/18d4b17070b9974149310c874286b074226fb8d4/Lib/fontTools/ufoLib/validators.py#L801) and [ufonormalizer](https://github.com/unified-font-object/ufoNormalizer/blob/4c0bc0242ed90119e08627c8d24057d46806d4b9/src/ufonormalizer/__init__.py#L1642).
- There would need to be a version bump because existing tools out there would be getting a new type of data. Anything that performs validation before reading is going to reject these new UFOs.
- If I were writing the spec, I'd put some information in about lossiness and make recommendations about how tools should minimize the risk. "Rewrite the original data JPEG rather than writing a new JPEG from the decoded JPEG." or something like that.
- Probably other stuff that I haven't thought of. (I'm really busy with my day job so I don't have time to work through all the implementation details. This is all off the top of my head.)

Is this a practical issue in one of your tools or just a general thought? I'm trying to figure out how much breakage this is worth.

**Comment by justvanrossum** [comment]
If I want my tool to support JPEG (and I do), then I have two choices:

- Convert to PNG when writing to UFO
- Work on updating the spec, ufonormalizer and ufoLib

On the one hand I think it should be natural for UFO background images to be JPEG, and I'm willing to invest some effort. On the other hand, indeed: "how much breakage this is worth?".

I don't know yet...

I do have a question in the meantime. I see the spec doesn't require a `.png` filename extension, and ufoLib's validator peeks into the file to confirm the data is in PNG format. However, ufonormalizer *does* seem to only [take `*.png` into account](https://github.com/unified-font-object/ufoNormalizer/blob/4c0bc0242ed90119e08627c8d24057d46806d4b9/src/ufonormalizer/__init__.py#L1642-L1648).

This makes me think the spec should perhaps require the correct filename extension, especially if/once we'd allow JPEG in addition to PNG.

**Comment by typesupply** [comment]
> Convert to PNG when writing to UFO

This seems like the easiest to do. It may be what RoboFont does. I frequently copy image details from Preview or Photoshop and paste them directly into RF. It never occurred to me until just now that the pasteboard data probably isn't PNG. I think RF will let you drag image types into the editor and it converts them to PNG on save.

Is there anything fundamentally better about JPEG than PNG? File size for large images and general ubiquity are the only advantages I remember. I used to do a lot of drawing on paper, then scan them, then put them in the background for tracing. I never used JPEG because of the lossiness. I'd always save as uncompressed TIFF or TIFF with LZW if the image was huge. These days I do a lot of drawing on an iPad and the default export format is PNG.

> This makes me think the spec should perhaps require the correct filename extension, especially if/once we'd allow JPEG in addition to PNG.

I agree. I should have added this. Sorry about the oversight.

**Comment by justvanrossum** [comment]
In my case, the images may travel over a network, so file size may be a more important factor for me than for others.

I imagine people taking a quick photo of a sketch and wanting to use that as a background image. Image quality and lossiness don't seem important factors to me in such a case.

But perhaps I'm overestimating the need for JPEG to be stored in UFO.

**Comment by justvanrossum** [comment]
I bow down to the spec and will stick with PNG for storage in UFO. I will (at least for now) not persue expanding the spec and implementations to also accept JPEG.

I'm closing this, but feel free to reopen in case you feel that eventually this should be done.
