### ISSUE TITLE
Store color tuple as integers?

### ISSUE THREAD

**Issue by madig** [unified-font-object/ufo-spec#61]
I'm trying to track down an annoying rounding issue when converting between Glyphs files (uses an integer tuple to specify the RGBA values) and UFOs (floats), which made me wonder: why does the spec mandate floats instead of easier-to-handle-because-no-rounding-issues integers?

**Comment by typesupply** [comment]
Because if we picked integers someone would ask why we didn't pick floats. :)

There are lots of color representation models. We went with floats.

**Comment by madig** [comment]
Alright. Is there a preferred number y I can pass to round(x, y) to get a normalized float?

**Comment by typesupply** [comment]
We don't define a preferred number of digits after the decimal, if that's what you mean. The ufoNormalizer handles this [here](https://github.com/unified-font-object/ufoNormalizer/blob/master/src/ufonormalizer.py#L1040).

**Comment by justvanrossum** [comment]
It is trivial to losslessly convert 0..255 RGBA int values to and from 0..1 RGBA float values. So something must be screwing up somewhere.

**Comment by anthrotype** [comment]
hm, maybe it's because of python3 "banker's" `round` that does ROUND_HALF_EVEN?
https://github.com/googlei18n/glyphsLib/blob/06779fd3cfa493ee480281cf87ea03dd404525e9/Lib/glyphsLib/builder/glyph.py#L255

**Comment by anthrotype** [comment]
or more likely, it's because they are serializing the RGBA color floats with only 4 decimal digits, so they lose precision and can't be roundtripped
https://github.com/googlei18n/glyphsLib/blob/06779fd3cfa493ee480281cf87ea03dd404525e9/Lib/glyphsLib/builder/glyph.py#L52

personally, I would just use python own `repr`/`float` which are guaranteed to roundtrip, and also give the shortest representation.

**Comment by justvanrossum** [comment]
Even with only 3 decimal digits you can roundtrip:

```python
for i in range(256):
    f = i / 255
    r = "%.3f" % f
    f2 = float(r)
    i2 = round(f2 * 255)
    assert i == i2
    print(i, f, r, f2, i2)
```

**Comment by anthrotype** [comment]
Thanks Just.. I spoke before checking 😅

**Comment by anthrotype** [comment]
But only if you start with int, you can round trip. If you start with a color float with arbitrary precision that happens to be in between the 1/255 fractions then it’s impossible to round trip back to the same float. I guess for the sake of roundtrippability one may restrict oneself to the color space defined by the 0..255 int values, and serialise the float so that they are rounded to the closest of these fractional values.

**Comment by typesupply** [comment]
It seems like we're agreed that this is not an issue with the UFO spec, so I'm going to close this.

**Comment by madig** [comment]
@anthrotype The restricting part would have to be done on the UFO side before going to Glyphs, no? Going from Glyphs to UFO means overwriting whatever is in the UFO with 1/255th float things.

**Comment by justvanrossum** [comment]
If the author of the UFO file cares about round tripping to Glyphs, then yes, they should round their color values to 1/255 steps in the UFO.

**Comment by anthrotype** [comment]
yes, that's what I meant, thanks Just and Tal
