### ISSUE TITLE
openTypeNamePreferred*Name clarification

### ISSUE THREAD

**Issue by bobh0303** [unified-font-object/ufo-spec#64]
It seems to me, and experience so far confirms, that in fontinfo.plist the four fields:

- `familyName`
- `styleName`
- `styleMapFamilyName`
- `styleMapStyleName`

are sufficient to determine, for OpenType font name tables:
- what goes in name IDs 1 and 2, 
- whether name IDs  16 and 17 are needed, and if so:
- what goes in name IDs 16 and 17

That being the case, what is the purpose of the two fields:
- `openTypeNamePreferredFamilyName`
- `openTypeNamePreferredSubfamilyName`

and maybe more importantly should happen if these two sets of values don't agree?

**Comment by typesupply** [comment]
As with issue #63, the UFO spec doesn't have an answer to this by design. Naming is/was one of the most subjective areas of compiling font binaries. Making something work in one environment often makes it not work in another environment. _(cough Microsoft Word cough)_

That said, it's my experience as well that those four fields are almost always sufficient. My [ufo2fdk](https://github.com/typesupply/ufo2fdk) package has the recipe that I have been using for a long time.

**Comment by bobh0303** [comment]
Thanks for your explanations, which I interpret to say: When creating an OpenType font from a UFO, the `openType*` fields override any related generic fields.

While the above is probably obvious to everyone who has been involved in UFO development, does the spec actually _say_ this is the way it works? If not, other noobs may, like I did, look at the spec and think there are redundant and possibly conflicting fields defined by it.
